// AUTO-GENERATED FILE - DO NOT MODIFY DIRECTLY
// Generated by proto/build-proto.js

import { Controller } from "./index"
import { StreamingResponseHandler } from "./grpc-handler"
import { handleAccountServiceRequest, handleAccountServiceStreamingRequest } from "./account/index"
import { handleBrowserServiceRequest, handleBrowserServiceStreamingRequest } from "./browser/index"
import { handleCheckpointsServiceRequest, handleCheckpointsServiceStreamingRequest } from "./checkpoints/index"
import { handleFileServiceRequest, handleFileServiceStreamingRequest } from "./file/index"
import { handleMcpServiceRequest, handleMcpServiceStreamingRequest } from "./mcp/index"
import { handleStateServiceRequest, handleStateServiceStreamingRequest } from "./state/index"
import { handleTaskServiceRequest, handleTaskServiceStreamingRequest } from "./task/index"
import { handleWebServiceRequest, handleWebServiceStreamingRequest } from "./web/index"
import { handleModelsServiceRequest, handleModelsServiceStreamingRequest } from "./models/index"
import { handleSlashServiceRequest, handleSlashServiceStreamingRequest } from "./slash/index"

/**
 * Configuration for a service handler
 */
export interface ServiceHandlerConfig {
	requestHandler: (controller: Controller, method: string, message: any) => Promise<any>
	streamingHandler: (
		controller: Controller,
		method: string,
		message: any,
		responseStream: StreamingResponseHandler,
		requestId?: string,
	) => Promise<void>
}

/**
 * Map of service names to their handler configurations
 */
export const serviceHandlers: Record<string, ServiceHandlerConfig> = {
	"clineShengsuan.AccountService": {
		requestHandler: handleAccountServiceRequest,
		streamingHandler: handleAccountServiceStreamingRequest,
	},
	"clineShengsuan.BrowserService": {
		requestHandler: handleBrowserServiceRequest,
		streamingHandler: handleBrowserServiceStreamingRequest,
	},
	"clineShengsuan.CheckpointsService": {
		requestHandler: handleCheckpointsServiceRequest,
		streamingHandler: handleCheckpointsServiceStreamingRequest,
	},
	"clineShengsuan.FileService": {
		requestHandler: handleFileServiceRequest,
		streamingHandler: handleFileServiceStreamingRequest,
	},
	"clineShengsuan.McpService": {
		requestHandler: handleMcpServiceRequest,
		streamingHandler: handleMcpServiceStreamingRequest,
	},
	"clineShengsuan.StateService": {
		requestHandler: handleStateServiceRequest,
		streamingHandler: handleStateServiceStreamingRequest,
	},
	"clineShengsuan.TaskService": {
		requestHandler: handleTaskServiceRequest,
		streamingHandler: handleTaskServiceStreamingRequest,
	},
	"clineShengsuan.WebService": {
		requestHandler: handleWebServiceRequest,
		streamingHandler: handleWebServiceStreamingRequest,
	},
	"clineShengsuan.ModelsService": {
		requestHandler: handleModelsServiceRequest,
		streamingHandler: handleModelsServiceStreamingRequest,
	},
	"clineShengsuan.SlashService": {
		requestHandler: handleSlashServiceRequest,
		streamingHandler: handleSlashServiceStreamingRequest,
	},
}
